name: Scavengerhunt
api-version: 1.16
main: me.miqhtie.ScavengerHunt
version: 1.0
description: Scavenger hunt plugin for Calm Guild
author: Miqhtie

commands:
  setitems:
    description: Set the items for the scavenger hunt
  start:
    description: Starts the game
  end:
    description: Ends the game
  items:
    description: View the items you need to collect